### ISSUE TITLE
Dependencies in package.json are borked

### ISSUE THREAD

**Issue by gilzow** [platformsh-templates/strapi4#41]
### Describe the bug

yes, that's the technical term 😛 

whenever our auto-upgrade process kicks off, the app fails to build complaining that 
`ModuleNotFoundError: Module not found: Error: Can't resolve 'react/jsx-runtime'`
This appears to be an issue with how some of the dependencies in the current package.json are pinned to v4.3.2 while others are only constrained to the major version (ie ^4.3.2).

When we do `yarn upgrade` as part of our upgrade process, the unconstrained dependencies are being upgraded, along with their defined dependencies. As an example, in the current working version, `strapi/icons` is at v1.2.0 and [its package.json](https://www.npmjs.com/package/@strapi/icons/v/1.2.0?activeTab=code) file does **not** include `"type": "module"`. However, during `yarn upgrade` it is upgraded (as a dependency of @strapi/admin which is updated to 4.9.1) to v1.6.6 where now [its package.json ](https://www.npmjs.com/package/@strapi/icons?activeTab=code) _does_ include `"type": "module"`. 

Unpinning @strapi/strapi and the other @strapi dependencies allows `yarn/strapi` build to complete successfully.  

### Include some logs

```
    Building your admin UI with development configuration...
    ℹ Compiling Webpack
    W: ModuleNotFoundError: Module not found: Error: Can't resolve 'react/jsx-runtime' in '/app/node_modules/@strapi/icons/dist'
    W: Did you mean 'jsx-runtime.js'?
    W: BREAKING CHANGE: The request 'react/jsx-runtime' failed to resolve only because it was resolved as fully specified
    W: (probably because the origin is strict EcmaScript Module, e. g. a module with javascript mimetype, a '*.mjs' file, or a '*.js' file where the package.json contains '"type": "module"').
    W: The extension in the request is mandatory for it to be fully specified.
    W: Add the extension to the request.
    W:     at /app/node_modules/webpack/lib/Compilation.js:2016:28
    W:     at /app/node_modules/webpack/lib/NormalModuleFactory.js:805:13
    W:     at eval (eval at create (/app/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:10:1)
    W:     at /app/node_modules/webpack/lib/NormalModuleFactory.js:272:22
    W:     at eval (eval at create (/app/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:9:1)
    W:     at /app/node_modules/webpack/lib/NormalModuleFactory.js:436:22
    W:     at /app/node_modules/webpack/lib/NormalModuleFactory.js:118:11
    W:     at /app/node_modules/webpack/lib/NormalModuleFactory.js:677:25
    W:     at /app/node_modules/webpack/lib/NormalModuleFactory.js:881:8
    W:     at /app/node_modules/webpack/lib/NormalModuleFactory.js:1001:5
    W: resolve 'react/jsx-runtime' in '/app/node_modules/@strapi/icons/dist'
    W:   Parsed request is a module
    W:   using description file: /app/node_modules/@strapi/icons/package.json (relative path: ./dist)
```

### Reproducing

1. run `yarn upgrade`
2. commit updated yarn.lock
3. deploy so `yarn build` is executed in the build hook

### Expected behavior

Build successfully

### Your environment

N/A

**Comment by gilzow** [comment]
Closes via #42
